// films/src/app/components/films/films.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { IFilm } from 'src/app/models/film';
import { FilmsService } from 'src/app/services/films.service';

@Component({
  selector: 'app-films',
  templateUrl: './films.component.html',
  styleUrls: ['./films.component.css']
})
export class FilmsComponent implements OnInit {

  public name: string;
  
  public year: number;

  public producer: string;

  public editName: string;
  
  public editYear: number;

  public editProducer: string;

  public films: IFilm[];

  private _filmToEdit: IFilm;

  constructor(private filmsService: FilmsService) { }

  ngOnInit(): void {
    this.films = this.filmsService.getAllFilms();
  }

  createFilm() {
      
      const film: IFilm = {
        name: this.name,
        producer: this.producer,
        year: this.year,
        actors: []
      }

      this.films.push(film);
  }

  onChange(value: string)
  {
    this._filmToEdit = this.films.filter(x => x.name == value)[0];

    if (!this._filmToEdit)
    {
      this.editName = "";
      this.editYear = null;
      this.editProducer = "";
      return;
    }


    this.editName = this._filmToEdit.name;
    this.editYear = this._filmToEdit.year;
    this.editProducer = this._filmToEdit.producer;
  }

  editFilm() 
  {
    if(!this._filmToEdit)
      return;

    this._filmToEdit.name = this.editName;
    this._filmToEdit.year = this.editYear;
    this._filmToEdit.producer = this.editProducer;
  }

}

<div *ngFor="let film of films"  style="margin-bottom: 20px;">
    <div>Назва: {{film.name}}</div>
    <div>Рік: {{film.year}}</div>
    <div>Продюсер: {{film.producer}} </div>
    Актори:
    <div *ngFor="let actor of film.actors">
        <div>Ім'я: {{actor.name}}</div>
        <div>Персонаж: {{actor.character}}</div>
    </div>
</div>

<div style="margin-bottom: 20px;">
    <div>Назва: <input [(ngModel)]="name"> </div>
    <div>Рік: <input type="number" [(ngModel)]="year"> </div>
    <div>Продюсер:  <input [(ngModel)]="producer"> </div>
    <button (click)="createFilm()">Створити</button>
</div>

<select (change)="onChange($event.target.value)">
    <option key="empty"></option>
    <option *ngFor="let film of films" key="film.name">{{film.name}}</option>
</select>

<div>
    <div>Назва: <input [(ngModel)]="editName"> </div>
    <div>Рік: <input type="number" [(ngModel)]="editYear"> </div>
    <div>Продюсер:  <input [(ngModel)]="editProducer"> </div>
    <button (click)="editFilm()">Редагувати</button>
</div>

// films-react/src/components/Films.js
import FilmsService from '../services/FilmsService';
import React, { Component } from 'react';

class Films extends Component{

    constructor() {
      super();

      this.state = {films:new FilmsService().getAllFilms()}
    }

    render() {
        return (
            <div>
            {this.state.films.map(film => (
                <div style={{marginBottom: 20 + "px"}}>
                <div>Назва: {film.name}</div>
                <div>Рік: {film.year}</div>
                <div>Продюсер: {film.producer} </div>
                Актори:
                {film.actors.map(actor => (
                    <div>
                         <div>Ім'я: {actor.name}</div>
                         <div>Персонаж: {actor.character}</div>
                    </div>
                ))}
                </div>
            ))}
    
        <div style={{marginBottom: 20 + "px"}}>
            <div>Назва: <input /> </div>
            <div>Рік: <input type="number"/> </div>
            <div>Продюсер:  <input/> </div>
            <button>Створити</button>
        </div>
        
        <select >
            <option key="empty"></option>
            {
                this.state.films.map(film => (
                    <option key={film.name}>{film.name}</option>
                ))
            }
        </select>
        <div>
            <div>Назва: <input /> </div>
            <div>Рік: <input type="number"  /> </div>
            <div>Продюсер:  <input /> </div>
            <button >Редагувати</button>
        </div>
        </div>
        );
    }
}

export default Films;
